---
# Containers are under development
containers:
  - name: broker
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - name: broker
        containerPort: 9092
        protocol: TCP
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_BROKER_ID: "1"
    volumeMounts:
       - name: kafka-varlog
         mountPath: /var/log/kafka/
    volumes:
      - name: kafka-varlog
        emptyDir: {}
    memory: 4Gi
    services:
      - name: broker
        ports:
          - port: 9092
            protocol: TCP
            targetPort: 9092
            name: broker

  - name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - name: zookeeper
        containerPort: 2181
        protocol: TCP
    environment:
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_CLIENT_PORT: "2181"
    volumeMounts:
       - name: kafka-varlog
         mountPath: /var/log/kafka/
    volumes:
      - name: kafka-varlog
        emptyDir: {}

    memory: 4Gi
    services:
      - name: zookeeper
        ports:
          - port: 2181
            protocol: TCP
            targetPort: 2181
            name: zookeeper

virtualmachines:
  - name: "webserver"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
    services:
      - name: webserver-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: webserver
    routes:
      - name: webserver-web
        host: webserver
        service: webserver-http
        targetPort: 80
        tls: true
        tls_termination: Edge
